### ISSUE TITLE
How to add dependency to client handler?

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deepcase#60]
We have added dependency this way: https://github.com/deep-foundation/deepcase/compare/main...LiKissDmd:deepcase:main

Here is client handler code:
```tsx
async ({ deep, require }) => {
  const React = require('react');
  const { Box,Button } = require('@chakra-ui/react');
  const { generateMessages, getAllCoolOrders } = require("@likissdmd/warframe-market-prime-trash-buyer")

  return ({ fillSize, style, link }) => {
    function buttonClickHandler(){
      const allCoolOrders = await getAllCoolOrders()
    const messages = generateMessages(allCoolOrders)
    }
    return <Box
        style={{ width: 300, height: 300, ...style }}
        bg={'bgColor'}
        color={'text'}
        borderColor={'borderColor'}
        borderWidth='thin'
        borderWidth='1px' borderRadius='lg'
        padding={1}
    >
<Button onClick={buttonClickHandler}>
Generate Messages
</Button>
    </Box>
  }
}
```

Nothing is showed in the preview. I think this is related to import. When we were trying to import this package in async docker handler (not client) we had error like "You are importing es module by using require, use async import instead (await import)) and we fixed that by using await import instead and it was working. await import here does not work

**Comment by Konard** [comment]
![Screenshot_20240131_150355](https://github.com/deep-foundation/deepcase/assets/1431904/d0405bf3-f14e-4a6c-955b-dbc223deebb2)

It is module, so looks like the correct way to add dependency to ClientHandler.

**Comment by FreePhoenix888** [comment]
# Working Client Handler Code (Without importing the library, with Importing other libraries by using require)
```tsx
async ({ deep, require }) => {
  const React = require('react');
  const { Box,Button } = require('@chakra-ui/react');
  // const { generateMessages, getAllCoolOrders } = require("@likissdmd/warframe-market-prime-trash-buyer")

  return ({ fillSize, style, link }) => {
    return <Box
        style={{ width: 300, height: 300, ...style }}
        bg={'bgColor'}
        color={'text'}
        borderColor={'borderColor'}
        borderWidth='thin'
        borderWidth='1px' borderRadius='lg'
        padding={1}
    >
<Button>
Generate Messages
</Button>
    </Box>
  }
}
```

# Not Working Client Handler Code (Importing the library by using require)
```tsx
async ({ deep, require }) => {
  const React = require('react');
  const { Box,Button } = require('@chakra-ui/react');
  const { generateMessages, getAllCoolOrders } = require("@likissdmd/warframe-market-prime-trash-buyer")

  return ({ fillSize, style, link }) => {
    return <Box
        style={{ width: 300, height: 300, ...style }}
        bg={'bgColor'}
        color={'text'}
        borderColor={'borderColor'}
        borderWidth='thin'
        borderWidth='1px' borderRadius='lg'
        padding={1}
    >
<Button>
Generate Messages
</Button>
    </Box>
  }
}
```
## Errors
<details>
  <summary>Errors</summary>
```
editor evalClientHandler error Error: Module not found: Can't resolve @likissdmd/warframe-market-prime-trash-buyer
    at r (client-handler.js:254:11)
    at eval (eval at <anonymous> (client-handler.js:1:1), <anonymous>:6:24)
    at eval (client-handler.js:24:33)
    at Generator.next (<anonymous>)
    at eval (client-handler.js:12:71)
    at new Promise (<anonymous>)
    at __awaiter (client-handler.js:8:12)
    at evalClientHandler (client-handler.js:17:12)
    at eval (client-handler.js:328:122)
    at Generator.next (<anonymous>)
    at eval (client-handler.js:75:71)
    at new Promise (<anonymous>)
    at __awaiter (client-handler.js:71:12)
    at evalClientHandler (client-handler.js:327:12)
    at CytoEditor._e (editor.js:286:75)
    at commitHookEffectListMount (react-dom.development.js:23145:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24921:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24886:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24873:7)
    at commitPassiveMountEffects (react-dom.development.js:24861:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27034:3)
    at flushPassiveEffects (react-dom.development.js:26979:14)
    at performSyncWorkOnRoot (react-dom.development.js:26071:3)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at commitRootImpl (react-dom.development.js:26954:3)
    at commitRoot (react-dom.development.js:26677:5)
    at finishConcurrentRender (react-dom.development.js:25976:9)
    at performConcurrentWorkOnRoot (react-dom.development.js:25804:7)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)
```

</details>

# Working Client Handler Code (Importing other libraries by using await deep.import)
```tsx
async ({ deep, require }) => {
  const React = await deep.import('react');
  const { Box,Button } = await deep.import('@chakra-ui/react');
  // const { generateMessages, getAllCoolOrders } = require("@likissdmd/warframe-market-prime-trash-buyer")

  return ({ fillSize, style, link }) => {
    return <Box
        style={{ width: 300, height: 300, ...style }}
        bg={'bgColor'}
        color={'text'}
        borderColor={'borderColor'}
        borderWidth='thin'
        borderWidth='1px' borderRadius='lg'
        padding={1}
    >
<Button>
Generate Messages
</Button>
    </Box>
  }
}
```

# Not Working Client Handler Code (Importing the library by using await deep.import)
```tsx
async ({ deep, require }) => {
  const React = await deep.import('react');
  const { Box,Button } = await deep.import('@chakra-ui/react');
  const { generateMessages, getAllCoolOrders } = await deep.import("@likissdmd/warframe-market-prime-trash-buyer")

  return ({ fillSize, style, link }) => {
    return <Box
        style={{ width: 300, height: 300, ...style }}
        bg={'bgColor'}
        color={'text'}
        borderColor={'borderColor'}
        borderWidth='thin'
        borderWidth='1px' borderRadius='lg'
        padding={1}
    >
<Button>
Generate Messages
</Button>
    </Box>
  }
}
```

## Errors:
<details>
  <summary>Errors</summary>
```
IGNORED ERROR: Call to DeepClient.resolveDependency is failed with Error: Module not found: Can't resolve @likissdmd/warframe-market-prime-trash-buyer
    at r (client-handler.js:254:11)
    at eval (client-handler.js:248:16)
    at Generator.next (<anonymous>)
    at eval (client-handler.js:75:71)
    at new Promise (<anonymous>)
    at __awaiter (client-handler.js:71:12)
    at _deep_foundation_deeplinks_imports_client__WEBPACK_IMPORTED_MODULE_2__.DeepClient.resolveDependency (client-handler.js:204:113)
    at DeepClient.eval (client.js:823:45)
    at Generator.next (<anonymous>)
    at eval (client.js:44:71)
    at new Promise (<anonymous>)
    at __awaiter (client.js:40:12)
    at DeepClient.import (client.js:820:16)
    at eval (eval at <anonymous> (client-handler.js:1:1), <anonymous>:6:41)
    at eval (client-handler.js:24:33)
    at Generator.next (<anonymous>)
    at eval (client-handler.js:12:71)
    at new Promise (<anonymous>)
    at __awaiter (client-handler.js:8:12)
    at evalClientHandler (client-handler.js:17:12)
    at eval (client-handler.js:328:122)
    at Generator.next (<anonymous>)
    at eval (client-handler.js:75:71)
    at new Promise (<anonymous>)
    at __awaiter (client-handler.js:71:12)
    at evalClientHandler (client-handler.js:327:12)
    at CytoEditor._e (editor.js:286:75)
    at commitHookEffectListMount (react-dom.development.js:23145:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24921:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24886:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24873:7)
    at commitPassiveMountEffects (react-dom.development.js:24861:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27034:3)
    at flushPassiveEffects (react-dom.development.js:26979:14)
    at performSyncWorkOnRoot (react-dom.development.js:26071:3)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at commitRootImpl (react-dom.development.js:26954:3)
    at commitRoot (react-dom.development.js:26677:5)
    at finishConcurrentRender (react-dom.development.js:25976:9)
    at performConcurrentWorkOnRoot (react-dom.development.js:25804:7)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)
```

</details>

**Comment by Konard** [comment]
@FreePhoenix888 use commands from this section: https://github.com/deep-foundation/dev?tab=readme-ov-file#workspaces

For example:
```
npm run workspace-install --workspace_arg=deepcase --package_arg="@likissdmd/warframe-market-prime-trash-buyer"
```

**Comment by FreePhoenix888** [comment]
> @FreePhoenix888 use commands from this section: https://github.com/deep-foundation/dev?tab=readme-ov-file#workspaces
> 
> For example:
> 
> ```
> npm run workspace-install --workspace_arg=deepcase --package_arg="@likissdmd/warframe-market-prime-trash-buyer"
> ```
> 
> This command should be executed in `dev` folder.
> 
> Note that `dev` repository should be forked too, `deepcase` itself is not enough.

Accodring to your answer I have checked out to main in deepcase, executed the command you provided in dev folder, but I still get the same error

**Comment by FreePhoenix888** [comment]
I am not sure how this error happens but I created a new gitpod workspace with deep and:
1. npm run workspace-install --workspace_arg=deepcase --package_arg="@likissdmd/warframe-market-prime-trash-buyer"
2. Go to deepcase and add package to client-handler.tsx as in pull request
3. Create tsx link with this code:
```
async ({ deep, require }) => {
  const React = require('react');
  const { Box,Button } = require('@chakra-ui/react');
  const importData = await deep.import("@likissdmd/warframe-market-prime-trash-buyer")
  console.log({importData}) 

  return ({ fillSize, style, link }) => {
    return <Box
        style={{ width: 300, height: 300, ...style }}
        bg={'bgColor'}
        color={'text'}
        borderColor={'borderColor'}
        borderWidth='thin'
        borderWidth='1px' borderRadius='lg'
        padding={1}
    >
<Button>
Generate Messages
</Button>
    </Box>
  }
}  
```
4. See error 
<details>
  <summary>Error</summary>

```
editor evalClientHandler error SyntaxError: Unexpected token '<'
    at eval (client-handler.js:15:1)
    at Generator.next (<anonymous>)
    at eval (client-handler.js:7:1)
    at new Promise (<anonymous>)
    at __awaiter (client-handler.js:3:1)
    at evalClientHandler (client-handler.js:12:1)
    at eval (client-handler.js:266:49)
    at Generator.next (<anonymous>)
    at eval (client-handler.js:7:1)
    at new Promise (<anonymous>)
    at __awaiter (client-handler.js:3:1)
    at evalClientHandler (client-handler.js:265:1)
    at CytoEditor._e (editor.js:252:26)
    at commitHookEffectListMount (react-dom.development.js:23145:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24921:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24886:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24873:7)
    at commitPassiveMountEffects (react-dom.development.js:24861:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27034:3)
    at flushPassiveEffects (react-dom.development.js:26979:14)
    at performSyncWorkOnRoot (react-dom.development.js:26071:3)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at commitRootImpl (react-dom.development.js:26954:3)
    at commitRoot (react-dom.development.js:26677:5)
    at finishConcurrentRender (react-dom.development.js:25976:9)
    at performConcurrentWorkOnRoot (react-dom.development.js:25804:7)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)
```

</details>

How is this possble? The same code cause different error in two deeps

**Comment by FreePhoenix888** [comment]
@Konard any updates on this?

**Comment by FreePhoenix888** [comment]
The same happening to another module I have used before for deep-memo:
```
IGNORED ERROR: Call to DeepClient.resolveDependency is failed with Error: Module not found: Can't resolve @pbe/react-yandex-maps
```

**Comment by Konard** [comment]
@FreePhoenix888 did you able to solve this issue? If not, then what exactly left to fix?

**Comment by FreePhoenix888** [comment]
> @FreePhoenix888 did you able to solve this issue? If not, then what exactly left to fix?

I should recheck it lates with exactly the same packages here
